### PR TITLE
Misc small improvements and fixes

### PR DESCRIPTION
**Pull request by KurtisVargas**
Fixed output file type.  Files were named mp4 but were actually mkv format.
Updated URL that is used to download
Moved redundant code into routines for easier updating
Audio will now specifically be AAC all the time (use to be usually aac, but not always)
Added support for Plex Server naming for TV shows ("/show/season x/show s1e1 - desc.mkv)

### CODE REVIEW

**Comment by ilyaz** [comment]
Awesome job. I'll try it out on my end and merge it asap. Great work!

**Comment by KurtisVargas** [comment]
Thanks.  I'm in process of further extending it - I commit'd some changes a couple of hours ago but no pull yet since it's very much a WIP.  You can get a feel for where I'm going by looking at it.

Thanks so much for developing this!

**Comment by KurtisVargas** [comment]
Done for now.  The final commit (85bff00) has decent description of changes.  I hope you find this useful and thanks again.

**Comment by ilyaz** [comment]
Great work man! I have merged this after some testing as it seems to be working great so far. When I get time I will attempt to add multisection support to the webui, however I believe this would require some further alterations to the project. Thanks for your work!

**Pull request merged**
